/**
 * TTS job status + error codes. Single source of truth (skills.md DRY):
 * the DB enum values are generated by Prisma; we re-export them so app code
 * and the database can never drift apart.
 */
import { TtsJobStatus, JobErrorCode } from '@prisma/client';

export { TtsJobStatus, JobErrorCode };

/** Statuses that a recovery scan may re-enqueue. */
export const RECOVERABLE_STATUSES: readonly TtsJobStatus[] = [
  TtsJobStatus.queued,
  TtsJobStatus.processing,
  TtsJobStatus.retrying,
];

/** Terminal statuses (never re-enqueued). */
export const TERMINAL_STATUSES: readonly TtsJobStatus[] = [
  TtsJobStatus.completed,
];

/** Free-form job event names (not a DB enum). */
export const JOB_EVENT_TYPE = {
  CREATED: 'created',
  ENQUEUED: 'enqueued',
  PROCESSING_STARTED: 'processing_started',
  MODEL_CALL_STARTED: 'model_call_started',
  MODEL_CALL_COMPLETED: 'model_call_completed',
  MODEL_CALL_FAILED: 'model_call_failed',
  AUDIO_STORED: 'audio_stored',
  COMPLETED: 'completed',
  RETRYING: 'retrying',
  FAILED: 'failed',
  RECOVERED: 're_enqueued_by_recovery',
  NOTIFICATION_SENT: 'notification_sent',
  NOTIFICATION_FAILED: 'notification_failed',
} as const;

export type JobEventType = (typeof JOB_EVENT_TYPE)[keyof typeof JOB_EVENT_TYPE];
